In [8]:
import numpy as np

In [25]:
# MC5, 99pg
P = np.array([ [0.7 ,0.3, 0, 0.],
               [0.5, 0.5, 0, 0],
               [0, 0, 0.5, 0.5 ], 
               [0, 0, 0.6, 0.4] ])

In [26]:
value, vector = np.linalg.eig(np.transpose(P)) # 첫어레이는 고유값, 뒤에는 v1, v2,v3이다
print(value)
print(vector) # 아이덴벡터는 가로로 나옴

[ 1.   0.2  1.  -0.1]
[[ 0.85749293 -0.70710678  0.          0.        ]
 [ 0.51449576  0.70710678  0.          0.        ]
 [ 0.          0.          0.76822128 -0.70710678]
 [ 0.          0.          0.6401844   0.70710678]]


In [27]:
# MC12, 100pg
P = np.array([ [0.2 ,0.2, 0.6, 0.],
               [0, 0.5, 0, 0.5],
               [0, 0, 1, 0], 
               [0, 0, 0, 1] ])

In [28]:
value, vector = np.linalg.eig(np.transpose(P)) # 첫어레이는 고유값, 뒤에는 v1, v2,v3이다
print(value)
print(vector) # 아이덴벡터는 가로로 나옴

[1.  0.5 1.  0.2]
[[ 0.          0.          0.          0.67719918]
 [ 0.          0.70710678  0.         -0.45146612]
 [ 0.          0.          1.         -0.50789938]
 [ 1.         -0.70710678  0.          0.28216632]]


In [45]:
# MC14, 103pg
P = np.array([ [0, 0.5, 0.5],
               [0.5, 0, 0.5],
               [0.5, 0.5, 0] ])

In [46]:
value, vector = np.linalg.eig(np.transpose(P)) # 첫어레이는 고유값, 뒤에는 v1, v2,v3이다
print(value)
print(vector) # 아이덴벡터는 가로로 나옴

#분포니까 정규화해서 1/3, 1/3, 1/3

[-0.5  1.  -0.5]
[[-0.81649658  0.57735027  0.19219669]
 [ 0.40824829  0.57735027 -0.7833358 ]
 [ 0.40824829  0.57735027  0.59113912]]


In [47]:
# MC15, 104pg
P = np.array([ [0, 1/3, 2/3],
               [2/3, 0, 1/3],
               [1/3, 2/3, 0] ])

In [48]:
value, vector = np.linalg.eig(np.transpose(P)) # 첫어레이는 고유값, 뒤에는 v1, v2,v3이다
print(value)
print(vector) # 아이덴벡터는 가로로 나옴

#분포니까 정규화해서 1/3, 1/3, 1/3

[ 1. +0.j         -0.5+0.28867513j -0.5-0.28867513j]
[[ 0.57735027+0.j  -0.28867513-0.5j -0.28867513+0.5j]
 [ 0.57735027+0.j   0.57735027+0.j   0.57735027-0.j ]
 [ 0.57735027+0.j  -0.28867513+0.5j -0.28867513-0.5j]]
