# BFS

너비우선탐색 알고리즘 : 그래프나 트리에서 가까운 노드부터 탐색하는 알고리즘

	• 큐(Queue) 사용: BFS는 큐를 사용하여 구현. 탐색을 시작할 노드를 큐에 넣고, 큐에서 노드를 하나씩 꺼내어 그 노드의 이웃 노드들을 모두 방문한다.
	• 너비 우선: BFS는 현재 노드에서 가까운 이웃 노드들을 모두 방문한 후에는 그 이웃 노드들의 이웃 노드들을 순차적으로 방문. 즉, 너비(가까운 노드들)를 우선적으로 탐색합니다.
	• 최단 경로 탐색: 시작 노드에서부터 각 노드까지의 최단 경로를 탐색한다.


In [102]:
import queue
import numpy as np

In [103]:
N = 8
Kmax = 4
K = np.array([1, 2, 4, 1, 1, 3, 1, 1])  # 이웃의 수

nn = np.empty([N, Kmax], int)
nn[0] = np.array([2, -1, -1, -1])
nn[1] = np.array([2, 5, -1, -1])
nn[2] = np.array([0, 1, 3, 4])
nn[3] = np.array([2, -1, -1, -1])
nn[4] = np.array([2, -1, -1, -1])
nn[5] = np.array([1, 6, 7, -1])
nn[6] = np.array([5, -1, -1, -1])
nn[7] = np.array([5, -1, -1, -1])

print(nn)

[[ 2 -1 -1 -1]
 [ 2  5 -1 -1]
 [ 0  1  3  4]
 [ 2 -1 -1 -1]
 [ 2 -1 -1 -1]
 [ 1  6  7 -1]
 [ 5 -1 -1 -1]
 [ 5 -1 -1 -1]]


In [112]:
# K : 이웃의 수, nn: 이웃들 , start : 그래프 출발점 ,discovered : 점이 발견
def bfs(K, nn, start, discovered):
    q = queue.Queue()
    q.put(start) # 빈 큐에 출발점 추가하고
    discovered[start] = True # 이 점을 발견 .
    while q.qsize()>0: # 큐에 원소가 남아있는 한
        element = q.get() # 큐에서 한 점을 뽑아서
        # print(element)
        for k in range(K[element]):
            neighbor = nn[element][k] # 그 이웃 각각에 대해
            if discovered[neighbor]==False: # 미발견이면
                q.put(neighbor) # 큐에 추가하고
                discovered[neighbor] = True # 이 점을 발견 .
                # print('----------------')

In [113]:
discovered = np.array([False] * N)
start = 0
bfs(K, nn, start, discovered)
print("Discovered:", discovered)

Discovered: [ True  True  True  True  True  True  True  True]


In [106]:
# K : 이웃의 수, nn: 이웃들 , start : 그래프 출발점 ,discovered : 점이 발견
def distance_bfs(K, nn, start, discovered):
    q = queue.Queue()
    q.put(start) # 빈 큐에 출발점 추가하고
    discovered[start] = 0
    while q.qsize()>0: # 큐에 원소가 남아있는 한
        element = q.get() # 큐에서 한 점을 뽑아서
        for k in range(K[element]):
            neighbor = nn[element][k] # 그 이웃 각각에 대해
            if discovered[neighbor]== -1: # 미발견이면
                q.put(neighbor) # 큐에 추가하고
                discovered[neighbor] = discovered[element] + 1 # 이 점을 발견 .
    return discovered

In [107]:
discovered = np.array([-1] * N)
start = 0
distance_bfs(K, nn, start, discovered)
print("Distance:", discovered)

Distance: [0 2 1 2 2 3 4 4]
